### PR TITLE
Task/add login ui

### PR DESCRIPTION
**Pull request by ashwinjv**

### CODE REVIEW

**Comment by ashwinjv** [comment]
[Add UI form for Login](https://trello.com/c/wt9rAJRT/43-add-ui-form-for-login)

**Comment by ashwinjv** [comment]
[Add a reactive form for login](https://trello.com/c/dYigoZ7Q/44-add-a-reactive-form-for-login)

**Comment by ashwinjv** [comment]
https://stackblitz.com/github/holyjim/cva/tree/task/add-login-ui

**Review by ervinebalo — APPROVED** [review]

**Comment by ashwinjv** [comment]
[Add profile ui](https://trello.com/c/TFQ0Zfcm/46-add-profile-ui)

**Pull request merged**
